//! `resolver.type: docusaurus` (SPEC §12): `sidebars.js` / `sidebars.ts`, tolerant of the
//! shorthand doc-id string, `{type: 'doc', id}`, `{type: 'category', label, items}` and
//! `{type: 'autogenerated', dirName}`.

use std::collections::{BTreeMap, BTreeSet};

use globset::GlobSet;

use super::navigation::{self, JsValue, LinkTarget, NavEntry};
use super::{Candidate, ResolveError, read_file};
use crate::config::Source;
use crate::sources::Checkout;

/// Default navigation files, tried in order, when `path` is not given.
const DEFAULT_PATHS: [&str; 2] = ["sidebars.js", "sidebars.ts"];

/// Content root doc ids resolve under (SPEC §12: `doc` ids resolve to `docs/<id>.md(x)`).
const DOCS_DIR: &str = "docs";

/// Build the candidate map, residue scope and navigation file path for a `docusaurus` source.
pub(super) fn plan(
    source: &Source,
    checkout: &Checkout,
    files: &[String],
    path: Option<&str>,
    scope: &[String],
) -> Result<(BTreeMap<String, Candidate>, GlobSet, String), ResolveError> {
    let nav_path = locate(&source.name, files, path)?;
    let text = read_file(checkout, &nav_path)?;
    let file_set: BTreeSet<String> = files.iter().cloned().collect();

    let root = navigation::parse_js_value(&text);
    let mut docs = Vec::new();
    let mut autogenerated = Vec::new();
    collect(&root, &[], &mut docs, &mut autogenerated);

    let mut candidates = BTreeMap::new();
    for entry in docs {
        let doc_type = navigation::doc_type_from_section(&entry.section);
        let candidate = |path: String, selected: bool| Candidate {
            path: path.clone(),
            title: entry.title.clone(),
            doc_type: doc_type.to_string(),
            section: entry.section.clone(),
            selected,
            context: String::new(),
        };
        match resolve_doc_id(&entry.target, &file_set) {
            LinkTarget::Resolved(p) => {
                candidates.insert(p.clone(), candidate(p, true));
            }
            LinkTarget::Unresolved(p) => {
                candidates.insert(p.clone(), candidate(p, false));
            }
            LinkTarget::Skipped => {}
        }
    }
    for (dir_name, section) in autogenerated {
        let dir = dir_name.trim_matches('/');
        let prefix = if dir.is_empty() {
            format!("{DOCS_DIR}/")
        } else {
            format!("{DOCS_DIR}/{dir}/")
        };
        let doc_type = navigation::doc_type_from_section(&section);
        for file in files {
            if file.starts_with(&prefix) && navigation::is_markdown_extension(file) {
                candidates.entry(file.clone()).or_insert_with(|| Candidate {
                    path: file.clone(),
                    title: String::new(),
                    doc_type: doc_type.to_string(),
                    section: section.clone(),
                    selected: true,
                    context: String::new(),
                });
            }
        }
    }
    let scope_set = navigation::scope_set(DOCS_DIR, scope)?;
    Ok((candidates, scope_set, nav_path))
}

/// Find the navigation file: `path` verbatim when given, else the first of [`DEFAULT_PATHS`]
/// that exists.
fn locate(source_name: &str, files: &[String], path: Option<&str>) -> Result<String, ResolveError> {
    if let Some(p) = path {
        return files
            .iter()
            .find(|f| f.as_str() == p)
            .cloned()
            .ok_or_else(|| ResolveError::Navigation {
                name: source_name.to_string(),
                message: format!("navigation file {p:?} not found"),
            });
    }
    for candidate in DEFAULT_PATHS {
        if files.iter().any(|f| f == candidate) {
            return Ok(candidate.to_string());
        }
    }
    Err(ResolveError::Navigation {
        name: source_name.to_string(),
        message: "no sidebars.js or sidebars.ts found".to_string(),
    })
}

/// Resolve a doc id to `docs/<id>.md` or `docs/<id>.mdx`.
fn resolve_doc_id(id: &str, files: &BTreeSet<String>) -> LinkTarget {
    let id = id.trim_start_matches('/').trim();
    if id.is_empty() {
        return LinkTarget::Skipped;
    }
    let md = format!("{DOCS_DIR}/{id}.md");
    if files.contains(&md) {
        return LinkTarget::Resolved(md);
    }
    let mdx = format!("{DOCS_DIR}/{id}.mdx");
    if files.contains(&mdx) {
        return LinkTarget::Resolved(mdx);
    }
    LinkTarget::Unresolved(md)
}

/// Walk a parsed sidebars tree. `docs` collects shorthand and `{type: 'doc', …}` entries;
/// `autogenerated` collects `(dirName, section)` pairs for entries whose Markdown is selected
/// by directory rather than by id.
fn collect(
    value: &JsValue,
    ancestors: &[String],
    docs: &mut Vec<NavEntry>,
    autogenerated: &mut Vec<(String, String)>,
) {
    match value {
        JsValue::Array(items) => {
            for item in items {
                collect(item, ancestors, docs, autogenerated);
            }
        }
        JsValue::Str(id) => docs.push(NavEntry {
            title: String::new(),
            target: id.clone(),
            section: ancestors.join(" > "),
        }),
        JsValue::Object(fields) => match value.get("type").and_then(JsValue::as_str) {
            Some("category") => {
                let label = value.get("label").and_then(JsValue::as_str).unwrap_or("");
                let mut next = ancestors.to_vec();
                if !label.is_empty() {
                    next.push(label.to_string());
                }
                if let Some(items) = value.get("items") {
                    collect(items, &next, docs, autogenerated);
                }
            }
            Some("doc") => {
                let id = value.get("id").and_then(JsValue::as_str).unwrap_or("");
                let label = value.get("label").and_then(JsValue::as_str).unwrap_or("");
                if !id.is_empty() {
                    docs.push(NavEntry {
                        title: label.to_string(),
                        target: id.to_string(),
                        section: ancestors.join(" > "),
                    });
                }
            }
            Some("autogenerated") => {
                let dir = value.get("dirName").and_then(JsValue::as_str).unwrap_or("");
                autogenerated.push((dir.to_string(), ancestors.join(" > ")));
            }
            _ => {
                // Not a recognised sidebar item shape: likely the outer map of sidebar name to
                // array of items, or an unrelated key. Recurse into every field to find it.
                for (_, v) in fields {
                    collect(v, ancestors, docs, autogenerated);
                }
            }
        },
        JsValue::Other => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use std::fs;

    fn source(resolver_yaml: &str) -> Source {
        let text = format!(
            "version: 1\nsources:\n  - name: docs\n    repo: https://github.com/o/r\n    ref: main\n    \
             resolver:\n{resolver_yaml}"
        );
        Config::from_yaml(&text).unwrap().sources.remove(0)
    }

    fn checkout(entries: &[(&str, &str)]) -> (tempfile::TempDir, Checkout) {
        let dir = tempfile::tempdir().unwrap();
        for (path, content) in entries {
            let full = dir.path().join(path);
            fs::create_dir_all(full.parent().unwrap()).unwrap();
            fs::write(full, content).unwrap();
        }
        let checkout = Checkout {
            root: dir.path().to_path_buf(),
            commit: "abc".to_string(),
        };
        (dir, checkout)
    }

    const SIDEBARS: &str = r"
module.exports = {
  tutorialSidebar: [
    'intro',
    'missing-doc',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/one',
        { type: 'doc', id: 'guides/two', label: 'Two' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        { type: 'autogenerated', dirName: 'reference' },
      ],
    },
  ],
};
";

    fn fixture_files() -> Vec<String> {
        vec![
            "sidebars.js".to_string(),
            "docs/intro.md".to_string(),
            "docs/guides/one.md".to_string(),
            "docs/guides/two.md".to_string(),
            "docs/reference/alpha.md".to_string(),
            "docs/reference/beta.md".to_string(),
            "docs/orphan.md".to_string(),
        ]
    }

    #[test]
    fn plans_shorthand_doc_category_and_autogenerated_entries() {
        let (_dir, co) = checkout(&[
            ("sidebars.js", SIDEBARS),
            ("docs/intro.md", "# Intro\n"),
            ("docs/guides/one.md", "# One\n"),
            ("docs/guides/two.md", "# Two\n"),
            ("docs/reference/alpha.md", "# Alpha\n"),
            ("docs/reference/beta.md", "# Beta\n"),
            ("docs/orphan.md", "# Orphan\n"),
        ]);
        let src = source("      type: docusaurus\n");
        let (candidates, scope, nav_path) = plan(&src, &co, &fixture_files(), None, &[]).unwrap();

        let intro = &candidates["docs/intro.md"];
        assert_eq!(intro.section, "", "top-level shorthand has no section");
        assert!(intro.selected);

        let missing = &candidates["docs/missing-doc.md"];
        assert!(!missing.selected, "shorthand id with no file is unresolved");

        let one = &candidates["docs/guides/one.md"];
        assert_eq!(one.section, "Guides");
        assert_eq!(one.doc_type, "tutorial");

        let two = &candidates["docs/guides/two.md"];
        assert_eq!(two.title, "Two", "doc label wins");
        assert_eq!(two.section, "Guides");

        let alpha = &candidates["docs/reference/alpha.md"];
        assert_eq!(alpha.section, "Reference");
        assert_eq!(alpha.doc_type, "reference");
        let beta = &candidates["docs/reference/beta.md"];
        assert_eq!(beta.section, "Reference");

        assert!(
            !candidates.contains_key("docs/orphan.md"),
            "orphan is residue, not selected"
        );
        assert!(scope.is_match("docs/orphan.md"));
        assert_eq!(nav_path, "sidebars.js");
    }

    #[test]
    fn locate_prefers_js_then_ts_and_errors_when_missing() {
        assert_eq!(
            locate("s", &["sidebars.ts".to_string()], None).unwrap(),
            "sidebars.ts"
        );
        assert_eq!(
            locate(
                "s",
                &["sidebars.js".to_string(), "sidebars.ts".to_string()],
                None
            )
            .unwrap(),
            "sidebars.js"
        );
        let err = locate("s", &[], None).unwrap_err();
        assert!(matches!(err, ResolveError::Navigation { .. }), "{err}");
    }

    #[test]
    fn resolve_doc_id_prefers_md_then_mdx_then_unresolved() {
        let files: BTreeSet<String> = ["docs/a.md", "docs/b.mdx"]
            .into_iter()
            .map(String::from)
            .collect();
        assert_eq!(
            resolve_doc_id("a", &files),
            LinkTarget::Resolved("docs/a.md".to_string())
        );
        assert_eq!(
            resolve_doc_id("b", &files),
            LinkTarget::Resolved("docs/b.mdx".to_string())
        );
        assert_eq!(
            resolve_doc_id("c", &files),
            LinkTarget::Unresolved("docs/c.md".to_string())
        );
        assert_eq!(resolve_doc_id("", &files), LinkTarget::Skipped);
    }
}
