//! End-to-end coverage of the built-in navigation resolvers (SPEC §12) against the fixtures
//! under `tests/fixtures/navigation/`: for each format, the pages a navigation file links are
//! selected with the right title, section and `doc_type`, unlinked Markdown in scope is residue,
//! and a dangling link is reported as unresolved.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use pinakes::config::Config;
use pinakes::manifest::{PageEntry, SelectedBy};
use pinakes::residue::Reason;
use pinakes::resolve::{self, ResolveContext};
use pinakes::sources::Checkout;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/navigation")
        .join(name)
}

fn source_for(resolver_yaml: &str) -> pinakes::config::Source {
    let text = format!(
        "version: 1\nsources:\n  - name: docs\n    repo: https://github.com/o/r\n    ref: main\n    \
         resolver:\n{resolver_yaml}"
    );
    Config::from_yaml(&text).unwrap().sources.remove(0)
}

fn resolve(root: &Path, resolver_yaml: &str) -> resolve::ResolvedSource {
    let source = source_for(resolver_yaml);
    let checkout = Checkout {
        root: root.to_path_buf(),
        commit: "0123456789abcdef0123456789abcdef01234567".to_string(),
    };
    let deny = pinakes::config::compile_globs("deny", &[]).unwrap();
    let decisions = BTreeMap::new();
    let ctx = ResolveContext {
        deny: &deny,
        deny_patterns: &[],
        decisions: &decisions,
        config_dir: Path::new("."),
        is_new_source: false,
    };
    resolve::resolve_source(&source, &checkout, &ctx).expect("resolve succeeds on the fixture")
}

fn page<'a>(pages: &'a BTreeMap<String, PageEntry>, path: &str) -> &'a PageEntry {
    pages
        .get(path)
        .unwrap_or_else(|| panic!("{path} is selected"))
}

fn residue_paths(result: &resolve::ResolvedSource, reason: Reason) -> Vec<&str> {
    result
        .residue
        .iter()
        .filter(|r| r.reason == reason)
        .map(|r| r.path.as_str())
        .collect()
}

/// The rule key (SPEC §2.4) recorded for the residue entry at `path`.
fn rule_key<'a>(result: &'a resolve::ResolvedSource, path: &str) -> &'a str {
    result
        .residue
        .iter()
        .find(|r| r.path == path)
        .and_then(|r| r.rule.as_ref())
        .unwrap_or_else(|| panic!("no residue entry (with a rule) for {path}"))
        .key
        .as_str()
}

#[test]
fn vitepress_resolver_selects_titles_sections_doc_types_residue_and_unresolved() {
    let result = resolve(&fixture("vitepress"), "      type: vitepress\n");

    let getting_started = page(&result.pages, "docs/guide/getting-started.md");
    assert_eq!(getting_started.title, "Getting Started");
    assert_eq!(getting_started.section, "Guide");
    assert_eq!(getting_started.doc_type, "tutorial");
    assert_eq!(getting_started.selected_by, SelectedBy::Resolver);

    let overview = page(&result.pages, "docs/guide/README.md");
    assert_eq!(
        overview.title, "Overview",
        "directory link resolves to README.md"
    );

    let deep = page(&result.pages, "docs/guide/advanced/deep.md");
    assert_eq!(deep.title, "Deep 'Dive'", "escaped quote is unescaped");
    assert_eq!(deep.section, "Guide > Advanced", "nested items group");

    let api = page(&result.pages, "docs/reference/api.md");
    assert_eq!(api.title, "API");
    assert_eq!(api.section, "Reference");
    assert_eq!(api.doc_type, "reference");

    assert_eq!(result.pages.len(), 4);
    assert_eq!(
        residue_paths(&result, Reason::NotSelected),
        ["docs/README.md"],
        "the landing page is not linked from the sidebar"
    );
    assert_eq!(result.unresolved, ["docs/reference/missing.md"]);
    assert_eq!(rule_key(&result, "docs/README.md"), "sidebar:unlinked");
    assert_eq!(
        rule_key(&result, "docs/reference/missing.md"),
        "nav:dangling-link"
    );
}

#[test]
fn vitepress_resolver_accepts_an_explicit_sidebar_path() {
    // The default config glob still matches, so pointing at it explicitly should resolve the
    // same navigation file.
    let result = resolve(
        &fixture("vitepress"),
        "      type: vitepress\n      path: docs/.vitepress/config.ts\n",
    );
    assert_eq!(result.pages.len(), 4);
}

#[test]
fn docusaurus_resolver_selects_shorthand_doc_category_and_autogenerated_entries() {
    let result = resolve(&fixture("docusaurus"), "      type: docusaurus\n");

    let intro = page(&result.pages, "docs/intro.md");
    assert_eq!(intro.section, "", "top-level shorthand has no section");
    assert_eq!(intro.doc_type, "concept");

    let one = page(&result.pages, "docs/guides/one.md");
    assert_eq!(one.section, "Guides");
    assert_eq!(one.doc_type, "tutorial");

    let two = page(&result.pages, "docs/guides/two.md");
    assert_eq!(
        two.title, "Two",
        "the doc label wins over an empty nav title"
    );
    assert_eq!(two.section, "Guides");

    let alpha = page(&result.pages, "docs/reference/alpha.md");
    assert_eq!(alpha.section, "Reference");
    assert_eq!(alpha.doc_type, "reference");
    let beta = page(&result.pages, "docs/reference/beta.md");
    assert_eq!(beta.section, "Reference");

    assert_eq!(result.pages.len(), 5);
    assert_eq!(
        residue_paths(&result, Reason::NotSelected),
        ["docs/orphan.md"]
    );
    assert_eq!(result.unresolved, ["docs/missing-doc.md"]);
    assert_eq!(rule_key(&result, "docs/orphan.md"), "docusaurus:unlinked");
    assert_eq!(
        rule_key(&result, "docs/missing-doc.md"),
        "nav:dangling-link"
    );
}

#[test]
fn mdbook_resolver_selects_parts_and_nesting_and_skips_drafts() {
    let result = resolve(&fixture("mdbook"), "      type: mdbook\n");

    let intro = page(&result.pages, "src/introduction.md");
    assert_eq!(
        intro.section, "",
        "content before the first part has no section"
    );

    let installation = page(&result.pages, "src/getting-started/installation.md");
    assert_eq!(installation.section, "Getting Started");
    assert_eq!(installation.doc_type, "tutorial");
    let advanced = page(&result.pages, "src/getting-started/advanced-options.md");
    assert_eq!(
        advanced.section, "Getting Started",
        "a nested list item, same part"
    );

    let cli = page(&result.pages, "src/reference/cli.md");
    assert_eq!(cli.title, "CLI Reference");
    assert_eq!(cli.section, "Reference");
    assert_eq!(cli.doc_type, "reference");

    assert_eq!(result.pages.len(), 5, "the draft chapter is not a page");
    assert_eq!(
        residue_paths(&result, Reason::NotSelected),
        ["src/SUMMARY.md", "src/orphan.md"],
        "SUMMARY.md itself is unlinked Markdown in scope, same as a resolver's own table of \
         contents (see the external resolver example in the README)"
    );
    assert_eq!(result.unresolved, ["src/reference/missing.md"]);
    assert_eq!(rule_key(&result, "src/SUMMARY.md"), "mdbook:unlinked");
    assert_eq!(rule_key(&result, "src/orphan.md"), "mdbook:unlinked");
    assert_eq!(
        rule_key(&result, "src/reference/missing.md"),
        "nav:dangling-link"
    );
}

#[test]
fn sitemap_resolver_maps_html_and_trailing_slash_urls_from_xml() {
    let result = resolve(
        &fixture("sitemap"),
        "      type: sitemap\n      url_prefix: 'https://example.com/docs/'\n      path_prefix: 'docs/'\n",
    );
    assert!(
        result.pages.contains_key("docs/guide/intro.md"),
        ".html maps to .md"
    );
    assert!(
        result.pages.contains_key("docs/guide/index.md"),
        "a trailing-slash url falls back to index.md"
    );
    assert!(result.pages.contains_key("docs/reference/api.md"));
    assert_eq!(result.pages.len(), 3);
    assert_eq!(
        residue_paths(&result, Reason::NotSelected),
        ["docs/orphan.md"]
    );
    assert_eq!(result.unresolved, ["docs/missing.md"]);
    assert_eq!(rule_key(&result, "docs/orphan.md"), "sitemap:unlisted");
    assert_eq!(rule_key(&result, "docs/missing.md"), "nav:dangling-link");
}

#[test]
fn sitemap_resolver_reads_a_plain_url_list_too() {
    let result = resolve(
        &fixture("sitemap"),
        "      type: sitemap\n      path: urls.txt\n      url_prefix: 'https://example.com/docs/'\n      \
         path_prefix: 'docs/'\n",
    );
    assert_eq!(result.pages.len(), 3);
    assert_eq!(
        residue_paths(&result, Reason::NotSelected),
        ["docs/orphan.md"]
    );
    assert_eq!(result.unresolved, ["docs/missing.md"]);
}
