module.exports = {
  tutorialSidebar: [
    'intro',
    'missing-doc',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/one',
        { type: 'doc', id: 'guides/two', label: 'Two' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        { type: 'autogenerated', dirName: 'reference' },
      ],
    },
  ],
};
